import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Banner from '../components/Banner';

export default function Home() {
  const handleOnClickBtnBanner = () => console.log('Hi, thanks for click me!');

  return (
    <div className={styles.container}>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="Discover your local coffee stores!"
          handleOnClick={handleOnClickBtnBanner}
        />
      </main>
    </div>
  );
}
